# Processing data

In [ ]:
from google.colab import files
files.upload()

Saving Istanbul Weather Data.csv to Istanbul Weather Data.csv


{'Istanbul Weather Data.csv': b'DateTime,Condition,Rain,MaxTemp,MinTemp,SunRise,SunSet,MoonRise,MoonSet,AvgWind,AvgHumidity,AvgPressure\r\n02.09.2019,Partly cloudy,0.00,27,22,06:32:00,19:37:00,9:52:00,21:45:00,23,66,1012\r\n01.09.2019,Partly cloudy,0.00,27,22,06:31:00,19:38:00,8:37:00,21:13:00,21,66,1011\r\n31.08.2019,Patchy rain possible,0.50,26,22,06:30:00,19:40:00,7:21:00,20:40:00,22,63,1015\r\n30.08.2019,Partly cloudy,0.00,27,22,06:29:00,19:42:00,6:4:00,20:5:00,20,64,1016\r\n29.08.2019,Partly cloudy,0.00,27,23,06:27:00,19:43:00,4:47:00,19:26:00,24,61,1015\r\n28.08.2019,Sunny,0.00,28,24,06:26:00,19:44:00,3:34:00,18:41:00,27,58,1016\r\n27.08.2019,Partly cloudy,0.00,30,24,06:25:00,19:46:00,2:27:00,17:50:00,27,61,1016\r\n26.08.2019,Sunny,0.00,30,24,06:24:00,19:47:00,1:31:00,16:51:00,25,66,1015\r\n25.08.2019,Partly cloudy,0.00,30,24,06:23:00,19:49:00,12:42:00,15:49:00,20,69,1015\r\n24.08.2019,Partly cloudy,0.00,30,24,06:22:00,19:50:00,12:3:00,14:45:00,19,71,1017\r\n23.08.2019,Partly clo

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd

df = pd.read_csv('Istanbul Weather Data.csv', sep=',')
df.head() #show the first 5 rows

DateTime             Condition  Rain  MaxTemp  MinTemp   SunRise  \
0  02.09.2019         Partly cloudy   0.0       27       22  06:32:00   
1  01.09.2019         Partly cloudy   0.0       27       22  06:31:00   
2  31.08.2019  Patchy rain possible   0.5       26       22  06:30:00   
3  30.08.2019         Partly cloudy   0.0       27       22  06:29:00   
4  29.08.2019         Partly cloudy   0.0       27       23  06:27:00   

     SunSet MoonRise   MoonSet  AvgWind  AvgHumidity  AvgPressure  
0  19:37:00  9:52:00  21:45:00       23           66         1012  
1  19:38:00  8:37:00  21:13:00       21           66         1011  
2  19:40:00  7:21:00  20:40:00       22           63         1015  
3  19:42:00   6:4:00   20:5:00       20           64         1016  
4  19:43:00  4:47:00  19:26:00       24           61         1015

In [ ]:
df = df[["Condition", "MinTemp", "AvgHumidity"]]
df.head()

Condition  MinTemp  AvgHumidity
0         Partly cloudy       22           66
1         Partly cloudy       22           66
2  Patchy rain possible       22           63
3         Partly cloudy       22           64
4         Partly cloudy       23           61

In [ ]:
df.shape #print the dimensions of this dframe

(3896, 3)

In [ ]:
df = df.dropna() #remove empty rows

#Convert each category into an interger
for ind in df.index:
  if df["Condition"][ind]=='Sunny':
    df["Condition"][ind] = 0
  elif df["Condition"][ind]=='Partly cloudy':
    df["Condition"][ind] = 1
  elif df["Condition"][ind]=='Cloudy':
    df["Condition"][ind] = 2
  elif df["Condition"][ind]=='Overcast':
    df["Condition"][ind] = 3
  elif df["Condition"][ind]=='Patchy rain possible':
    df["Condition"][ind] = 4
  else:
    df = df.drop([ind]) #we don't consider other classes so we drop it

#Cast this column to int
df["Condition"] = df["Condition"].astype(int)

df.head() #show the 5 first rows of the dataframe

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
<ipython-input-6-7ecef1bc3a9b>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Condition"][ind] = 0
<ipython-input-6-7ecef1bc3a9b>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Condition"][ind] = 0
<ipython-input-6-7ecef1bc3a9b>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Condition"][ind] = 0
<ipython-input-6-7ecef1bc3a9b>:6: SettingWithCopyWarning: 
A value 

Condition  MinTemp  AvgHumidity
0          1       22           66
1          1       22           66
2          4       22           63
3          1       22           64
4          1       23           61

In [ ]:
from keras.utils import to_categorical

labels = to_categorical(df.pop('Condition')) #Create classes from the labels

import numpy as np #import numpy library, used for arithmetic

features = np.array(df) #convert our dataframe into ndarray

In [ ]:
print(features)
print(labels)

[[22 66]
 [22 66]
 [22 63]
 ...
 [ 3 94]
 [ 1 89]
 [ 2 90]]
[[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]]


# Training the model

In [ ]:
import sklearn.metrics
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import activations
from tensorflow.keras import layers

NB_classes = 5 #number of outputs
NB_features = 2 #number of inputs
#Split 1 (85% vs 15%)
x_train, x_validate_test, y_train, y_validate_test = train_test_split(features, labels, test_size=0.15, shuffle=True)
#Split 2 (50% vs 50%)
x_test, x_validate, y_test, y_validate = train_test_split(x_validate_test, y_validate_test, test_size=0.50, shuffle=True)

In [ ]:
model = tf.keras.Sequential()
model.add(layers.Dense(12, activation='relu', input_shape=(NB_features,)))
model.add(layers.Dropout(0.2))
model.add(layers.Dense(NB_classes, activation=tf.keras.activations.softmax))

model.compile(optimizer="adam",loss=tf.keras.losses.categorical_crossentropy, metrics=['accuracy']) #compile the model
model.summary() #to see the param of our model

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 12)                36        
                                                                 
 dropout (Dropout)           (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 5)                 65        
                                                                 
Total params: 101 (404.00 Byte)
Trainable params: 101 (404.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
NUM_EPOCHS=20
BATCH_SIZE=10
history = model.fit(x_train, y_train, epochs=NUM_EPOCHS, batch_size=BATCH_SIZE, validation_data=(x_validate, y_validate))

Epoch 1/20
320/320 [==============================] - 3s 6ms/step - loss: 14.1423 - accuracy: 0.4254 - val_loss: 2.8602 - val_accuracy: 0.5936
Epoch 2/20
320/320 [==============================] - 2s 6ms/step - loss: 7.2471 - accuracy: 0.4395 - val_loss: 2.7466 - val_accuracy: 0.5795
Epoch 3/20
320/320 [==============================] - 2s 7ms/step - loss: 4.0771 - accuracy: 0.4798 - val_loss: 1.7013 - val_accuracy: 0.5583
Epoch 4/20
320/320 [==============================] - 2s 7ms/step - loss: 2.6275 - accuracy: 0.5155 - val_loss: 1.3324 - val_accuracy: 0.5936
Epoch 5/20
320/320 [==============================] - 2s 5ms/step - loss: 1.8893 - accuracy: 0.5486 - val_loss: 1.1164 - val_accuracy: 0.6042
Epoch 6/20
320/320 [==============================] - 1s 4ms/step - loss: 1.4617 - accuracy: 0.5699 - val_loss: 1.0776 - val_accuracy: 0.6042
Epoch 7/20
320/320 [==============================] - 2s 5ms/step - loss: 1.2090 - accuracy: 0.5952 - val_loss: 1.0807 - val_accuracy: 0.5936
Epoch

In [ ]:
performance=model.evaluate(x_test,y_test, batch_size=32, verbose=1, steps=None, )[1] * 100
print('Final accuracy : ', round(performance), '%')

9/9 [==============================] - 0s 3ms/step - loss: 0.9714 - accuracy: 0.6241
Final accuracy :  62 %


# Converting the model

In [ ]:
# #Generating a representative dataset function
# def representative_data_gen():
#   for i_value in tf.data.Dataset.from_tensor_slices(x_test).batch(1).take(100):
#     i_value_f32 = tf.dtypes.cast(i_value, tf.float32)
#     yield [i_value_f32]

# converter =tf.lite.TFLiteConverter.from_keras_model(model)

# #Representative dataset
# converter.representative_dataset = tf.lite.RepresentativeDataset(representative_data_gen)
# #Optimizations
# converter.optimizations = [tf.lite.Optimize.DEFAULT]
# #Supported ops
# converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# #Inference input/output type
# converter.inference_input_type = tf.int8
# converter.inference_output_type = tf.int8

# tflite_model_quant = converter.convert()
# #Save the converted model as .tflite
# open("rain_forecast_model.tflite", "wb").write(tflite_model_quant)
converter = tf.lite.TFLiteConverter.from_keras_model(model) #create a converter
tflite_model = converter.convert() #convert the model without quantization (for one of the next video)


open("rain_forecast_model.tflite","wb").write(tflite_model) #Create a file containing our tflite model

2092

In [ ]:
!apt-get update && apt-get -qq install xxd
!xxd -i rain_forecast_model.tflite > _model.h

Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:6 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:10 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,081 kB]
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [2,107 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security